### ISSUE TITLE
Issues while initial setup

### ISSUE THREAD

**Issue by Anurag870** [Kahoot-Clone/kahoot-clone#62]
I have 2 doubts in the initial setup

1) Which database to use to save quizzes? and how to install it. 

2) When I click on "Host" on "localhost:3000" it redirects to "http://localhost:3030/auth"  which is not found. 

Could you please suggest how to avoid these 2 issues.

**Comment by jshrc** [comment]
Were you able to resolve the installation issues? Could you provide any instruction/tips if so? Thanks!

**Comment by montoyaedu** [comment]
Hello!

I am addressing this problem in the open issue #63
